[build]
publish = "docs/dist"
command = "pnpm run deploy"

[build.environment]
NPM_FLAGS = "--version"
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "index.html"
status = 200

[[redirects]]
from = "/play/*"
to = "/play/index.html"
status = 200
