/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiTyping: typeof import('./.vitepress/theme/components/ApiTyping/index.vue')['default']
    HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
    MoreStarts: typeof import('./.vitepress/theme/components/MoreStarts.vue')['default']
    Repl: typeof import('./.vitepress/theme/components/repl/index.vue')['default']
  }
}
