name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[23]*'

jobs:
  release:
    strategy:
      matrix:
        vue-version: ['vue2', 'vue3']
        tag-prefix: ['v2', 'v3']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: cd packages/${{ matrix.vue-version }}
      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
